### ISSUE TITLE
parallel build fails

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#73]
**Reported by Daniel Russel on 27 Dec 38774889 04:00 UTC**
Attempting to do a parallel build with BALL 1.1.1 or 1.2 results in link errors, where as building
on the same platform not in parallel works just fine. i.e. "make -j 4" fails where as "make" works.
For example:
/flute1/home/drussel/src/BALL-1.2/source/SYSTEM/timer.C:406: multiple definition of
`BALL::Timer::dump(std::basic_ostream<char, std::char_traits<char> >&, unsigned int) const'
gcc 4.1 on Fedora 7. Ball 1.1.1 and BALL 1.2
