### PR TITLE
[Core] Fix for Quaternion class required from boost 1.66 upwards

### LINKED ISSUE #645: Build fails with clang-5.0.1: error: 'a' is a private member of 'boost::math::quaternion<float>'
```
In file included from /usr/ports/science/ball/work/ball-1_4_3-BETA1-749-g9a6dc8f82/source/STRUCTURE/structureMapper.C:10:
/usr/ports/science/ball/work/ball-1_4_3-BETA1-749-g9a6dc8f82/include/BALL/MATHS/quaternion.h:375:9: error: 'a' is a private member of 'boost::math::quaternion<float>'
                this->a = (T)1;
                      ^
/usr/ports/science/ball/work/ball-1_4_3-BETA1-749-g9a6dc8f82/include/BALL/MATHS/quaternion.h:294:9: note: in instantiation of member function 'BALL::TQuaternion<float>::setIdentity' requested here
                this->setIdentity();
                      ^
/usr/ports/science/ball/work/ball-1_4_3-BETA1-749-g9a6dc8f82/source/STRUCTURE/structureMapper.C:303:14: note: in instantiation of member function 'BALL::TQuaternion<float>::TQuaternion' requested here
                Quaternion rotation_quat;
                           ^
```

### PR DESCRIPTION
**Pull request by philthiel**
Boost quaterions make components a,b,c,d private starting from
version 1.66. Thus, adaptions to the BALL Quaternion class are
necessary including some small changes of the public interface.

This should fix #645

### CODE REVIEW

**Comment by philthiel** [comment]
I've tested the build with boost 1.66 locally on macOS. If somebody else with boost 1.66 can verify that it works would be great!

File: include/BALL/MATHS/quaternion.h [hunk 1]
```diff
@@ -200,7 +199,7 @@ namespace BALL
 		 * @param m the matrix to compute from
 		 * @return TMatrix4x4 the rotation matrix
 		 */
-		TMatrix4x4<T>& getRotationMatrix(TMatrix4x4<T>& m) const;
+		void getRotationMatrix(TMatrix4x4<T>& m) const;
```
Comment (tkemmer) [inline include/BALL/MATHS/quaternion.h]: Do we need to break the interface here? I get that the fixed class does no longer provide non-const refs to the quaternion components via its getters. But the change to this function here does not seem to be necessary.

(Also, the `@return` descriptions of the functions with modified interfaces are now incorrect.)

**Comment by tkemmer** [comment]
This PR also seems to work on my (linux) machine with boost 1.66. Did you plan to fully replace this PR by #648?
