### ISSUE TITLE
parallel build fails

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#73]
**Reported by Daniel Russel on 27 Dec 38774889 04:00 UTC**
Attempting to do a parallel build with BALL 1.1.1 or 1.2 results in link errors, where as building
on the same platform not in parallel works just fine. i.e. "make -j 4" fails where as "make" works.
For example:
/flute1/home/drussel/src/BALL-1.2/source/SYSTEM/timer.C:406: multiple definition of
`BALL::Timer::dump(std::basic_ostream<char, std::char_traits<char> >&, unsigned int) const'
gcc 4.1 on Fedora 7. Ball 1.1.1 and BALL 1.2

**Comment by anhi** [comment]
**Commented by admin on 26 May 38774890 15:06 UTC**
Parallel build is a bit complicated in BALL due to our use of subdirectories
(mostly for historical reasons). One day, we'll probably rewrite the whole build
system, but until then, you can use
make "MAKE=make -j4"
to achieve parallel builds.
